version: '3'
services: 
  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    volumes:
      - /home/borisavz/consul:/consul/data
  tracing:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
  app:
    build: .
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - consul
      - tracing
      - client
    environment:
      - DB=consul
      - DBPORT=8500

volumes:
  consul:
